name: build
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: lint linux
      uses: docker://golangci/golangci-lint:v1.31.0
      with:
        args: golangci-lint run
      env:
        CGO_ENABLED: 0
    - name: lint windows
      uses: docker://golangci/golangci-lint:v1.31.0
      with:
        args: golangci-lint run
      env:
        GOOS: windows
        CGO_ENABLED: 0
  test_with_coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: 1.15
    - name: Run Unit tests
      run: go test -covermode atomic -coverprofile=profile.cov $(go list -m)/...
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        GO111MODULE=off go get github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
  test:
    strategy:
      matrix:
        go-version: [1.15]
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - name: Run Unit tests
      run: go test ./...

